name: Self Hosted Deploy

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:  # Allows manual triggering

jobs:
    build-and-deploy:
        runs-on: self-hosted  # Uses your self-hosted runner
        environment: 'Self Hosted Production'
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
            
        - name: Deploy application
          run: |
            docker stop -f portfolio 2>/dev/null
            docker rm -f portfolio 2>/dev/null
            docker network prune -f 2>/dev/null
            docker build -t portfolio . && docker run --name portfolio -d -p 9099:80 portfolio