name: AWS production deploy
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: self-hosted
        environment: 'heynerserver'
        steps:
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Run with compose
          run: docker compose up -d